stages:
  - build

# Runtime platform: arch=amd64 os=windows pid=9900 revision=76984217 version=15.1.0
pages:
  stage: build
  tags:
    - Ubuntu
  script:
    # - powershell -command "Invoke-WebRequest -Uri https://github.com/rust-lang/mdBook/releases/download/v0.4.18/mdbook-v0.4.18-x86_64-pc-windows-msvc.zip -OutFile mdbook.zip"
    # - powershell -command "Invoke-WebRequest -Uri https://github.com/tommilligan/mdbook-admonish/releases/download/v1.7.0/mdbook-admonish-v1.7.0-x86_64-pc-windows-msvc.zip -OutFile mdbook-admonish.zip"
    # - powershell -command " Expand-Archive ./mdbook-admonish.zip ./assets"
    # - powershell -command " Expand-Archive ./mdbook.zip ./assets"
    # - ./assets/mdbook-admonish install --css-dir assets .
    - chmod u+x ./assets/mdbook
    - chmod u+x ./assets/mdbook-admonish
    - sudo mv ./assets/mdbook /usr/local/bin
    - sudo mv ./assets/mdbook-admonish /usr/local/bin
    - mdbook build -d public
  artifacts:
    paths:
      - public
  only:
    - main

#Runtime platform arch=amd64 os=linux pid=7468 revision=32fc1585 version=15.2.1
server:
  stage: build
  tags:
    - Ubuntu
  before_script:
    - "command -v ssh-agent >/dev/null || ( apk add --update openssh )"
    - eval $(ssh-agent -s)
    - echo "$PRIVATEKEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $HOSTNAME >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no $USERNAME@$HOSTNAME 'cd /home/$USER/Projects/Notes && git pull && docker-compose down && docker build -t mraddict063/notes --rm . && docker rmi $(docker images --filter "dangling=true" -q --no-trunc) && docker-compose up -d && docker push mraddict063/notes && exit'
