# Runtime platform: arch=amd64 os=windows pid=9900 revision=76984217 version=15.1.0
stages:
  - build

pages:
  stage: build
  tags:
    - HIPAA
  script:
    # - powershell -command "Invoke-WebRequest -Uri https://github.com/rust-lang/mdBook/releases/download/v0.4.18/mdbook-v0.4.18-x86_64-pc-windows-msvc.zip -OutFile mdbook.zip"
    # - powershell -command "Invoke-WebRequest -Uri https://github.com/tommilligan/mdbook-admonish/releases/download/v1.7.0/mdbook-admonish-v1.7.0-x86_64-pc-windows-msvc.zip -OutFile mdbook-admonish.zip"
    # - powershell -command " Expand-Archive ./mdbook-admonish.zip ./bin"
    # - powershell -command " Expand-Archive ./mdbook.zip ./bin"
    # - ./bin/mdbook-admonish.exe install --css-dir assets .
    - ./bin/mdbook.exe build -d public
  artifacts:
    paths:
      - public
  only:
    - main
