stages:
  - build

pages:
  stage: build
  tags:
    - Ubuntu
  script:
    - mdbook build -d public
  artifacts:
    paths:
      - public
  only:
    - main

server:
  stage: build
  tags:
    - Ubuntu
  before_script:
    - "command -v ssh-agent >/dev/null || ( apk add --update openssh )"
    - eval $(ssh-agent -s)
    - echo "$PRIVATEKEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $HOSTNAME >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  # script:
  #   - ssh -o StrictHostKeyChecking=no $USERNAME@$HOSTNAME 'cd /home/$USER/Projects/Notes && git pull && docker-compose down && docker build -t mraddict063/notes --rm . && docker rmi $(docker images --filter "dangling=true" -q --no-trunc) && docker-compose up -d && docker push mraddict063/notes && exit'
