[book]
authors = ["MR-Addict"]
description = "我的笔记(方便施展Copy+Paste魔法)"
language = "zh-cn"
multilingual = false
src = "src"
title = "我的笔记"

[rust]
edition = "2021" # the default edition for code blocks

[build]
build-dir = "book"
create-missing = false
use-default-preprocessors = true

[output.html]
default-theme = "Light"
preferred-dark-theme = "Navy"
curly-quotes = true
mathjax-support = true
copy-fonts = true
no-section-label = false
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/mr-addict/notes"
additional-css = ["./assets/mdbook-admonish.css"]

[output.html.print]
enable = true

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "2.0.0" # do not edit: managed by `mdbook-admonish install`
